/*
   Copyright 2020 Scott Bezek and the splitflap contributors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// NOTE: THIS FILE IS AUTOGENERATED! DO NOT MODIFY!
// To update, run `firmware/src/generate_acceleration.py`

#ifndef ACCELERATION
#define ACCELERATION

namespace Acceleration {
    const PROGMEM uint16_t ACCEL_STEP_PERIODS[] = {1600, 10000, 9637, 9312, 9018, 8751, 8506, 8281, 8072, 7879, 7700, 7532, 7375, 7227, 7088, 6956, 6832, 6714, 6602, 6496, 6394, 6298, 6205, 6117, 6032, 5950, 5872, 5797, 5725, 5655, 5588, 5523, 5460, 5400, 5341, 5285, 5230, 5176, 5125, 5075, 5026, 4979, 4933, 4888, 4845, 4802, 4761, 4721};
    const uint8_t MAX_ACCEL_STEP = 47;
}
#endif
